# main.tf — Root Configuration
# Connects all modules. enable_* flags controlled via terraform.tfvars (generated by wizard.py)

terraform {
  required_version = ">= 1.10.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# --- VPC Module ---
module "vpc" {
  source     = "./modules/vpc"
  enable_vpc = var.enable_vpc
  vpc_cidr   = var.vpc_cidr
  tags       = var.tags
}

# --- EC2 Module ---
module "ec2" {
  source        = "./modules/ec2"
  enable_ec2    = var.enable_ec2
  instance_type = var.instance_type
  ami_id        = var.ami_id
  instance_name = var.instance_name
  subnet_id     = module.vpc.public_subnet_id
  vpc_id        = module.vpc.vpc_id
  tags          = var.tags
}

# --- S3 Module ---
module "s3" {
  source      = "./modules/s3"
  enable_s3   = var.enable_s3
  bucket_name = var.bucket_name
  tags        = var.tags
}

# --- IAM Module ---
module "iam" {
  source         = "./modules/iam"
  enable_iam     = var.enable_iam
  role_name      = var.role_name
  s3_bucket_name = var.bucket_name
  tags           = var.tags
}

# --- CloudWatch Module ---
module "cloudwatch" {
  source            = "./modules/cloudwatch"
  enable_cloudwatch = var.enable_cloudwatch
  enable_ec2        = var.enable_ec2
  alarm_email       = var.alarm_email
  instance_id       = module.ec2.instance_id
  tags              = var.tags
}

# --- Billing Module ---
module "billing" {
  source       = "./modules/billing"
  budget_limit = var.budget_limit
  budget_email = var.budget_email
}

# --- DynamoDB Module ---
module "dynamodb" {
  source          = "./modules/dynamodb"
  enable_dynamodb = var.enable_dynamodb
  table_name      = var.dynamodb_table_name
  hash_key        = var.dynamodb_hash_key
  tags            = var.tags
}
