# variables.tf — All Input Variables
# Populated by terraform.tfvars (generated by cli-wizard/wizard.py — GITIGNORED)

variable "aws_region" {
  description = "AWS region to deploy resources in."
  type        = string
  default     = "ap-south-1" # Mumbai — closest region for India
}

# --- Feature Flags ---
variable "enable_vpc" {
  description = "Whether to create the VPC and networking resources."
  type        = bool
  default     = false
}

variable "enable_ec2" {
  description = "Whether to create an EC2 instance."
  type        = bool
  default     = false
}

variable "enable_s3" {
  description = "Whether to create an S3 bucket."
  type        = bool
  default     = false
}

variable "enable_iam" {
  description = "Whether to create an IAM role."
  type        = bool
  default     = false
}

variable "enable_cloudwatch" {
  description = "Whether to create CloudWatch alarms."
  type        = bool
  default     = false
}

# --- VPC ---
variable "vpc_cidr" {
  description = "CIDR block for the VPC."
  type        = string
  default     = "10.0.0.0/16"
}

# --- EC2 ---
variable "instance_type" {
  description = "EC2 instance type. Use t2.micro for free tier."
  type        = string
  default     = "t2.micro"
}

variable "ami_id" {
  description = "AMI ID for the EC2 instance. Use region-appropriate Amazon Linux 2 AMI."
  type        = string
  default     = ""
}

# --- S3 ---
variable "bucket_name" {
  description = "Name for the S3 bucket. Must be globally unique."
  type        = string
  default     = ""
}

# --- IAM ---
variable "role_name" {
  description = "Name for the IAM role."
  type        = string
  default     = "app-role"
}

# --- CloudWatch ---
variable "alarm_email" {
  description = "Email address for CloudWatch alarm notifications."
  type        = string
  default     = ""
}

# --- Billing ---
variable "budget_limit" {
  description = "Monthly budget limit in USD. Alert sent when exceeded."
  type        = string
  default     = "1"
}

variable "budget_email" {
  description = "Email address for billing budget alerts."
  type        = string
  default     = ""
}

# --- Shared ---
variable "tags" {
  description = "Tags applied to all resources for cost attribution and governance."
  type        = map(string)
  default     = {}
}
