#!/usr/bin/env python3
"""drift-detection/remediation.py — Automated infrastructure drift remediation.

This helper reads the drift report produced by drift-detection/detect.sh and,
when drift is confirmed, runs Terraform to restore the desired state.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence


@dataclass(slots=True)
class RemediationResult:
    """Outcome of a remediation attempt."""

    success: bool
    performed: bool
    message: str
    report_path: Path


def read_text_file(file_path: Path) -> str:
    """Read a text file and return an empty string when it does not exist."""
    if not file_path.exists():
        return ""
    return file_path.read_text(encoding="utf-8")


def report_contains_drift(report_text: str) -> bool:
    """Check whether a drift report indicates real drift."""
    normalized = report_text.upper()
    return "STATUS: DRIFT DETECTED" in normalized


def run_command(command: Sequence[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    """Run a subprocess command with captured text output."""
    return subprocess.run(
        list(command),
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=False,
    )


def write_report(report_path: Path, title: str, lines: Sequence[str]) -> None:
    """Write a remediation report file."""
    report_path.write_text(
        "\n".join([
            "# Drift Remediation Report",
            f"Timestamp: {datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"Status: {title}",
            "",
            *lines,
        ])
        + "\n",
        encoding="utf-8",
    )


def remediate_drift(
    project_root: Path,
    report_file: Path,
    terraform_binary: str = "terraform",
    auto_approve: bool = False,
) -> RemediationResult:
    """Remediate drift when a drift report confirms changes are needed."""
    remediation_report = project_root / "drift-remediation-report.txt"
    report_text = read_text_file(report_file)

    if not report_contains_drift(report_text):
        message = "No drift detected in report; remediation skipped."
        write_report(remediation_report, "SKIPPED", [message])
        return RemediationResult(True, False, message, remediation_report)

    if not auto_approve:
        message = "Auto-approval disabled; remediation skipped."
        write_report(remediation_report, "SKIPPED", [message])
        return RemediationResult(True, False, message, remediation_report)

    init_command = [terraform_binary, "init", "-input=false", "-no-color"]
    init_result = run_command(init_command, cwd=project_root)
    if init_result.returncode != 0:
        message = "terraform init failed during remediation."
        write_report(
            remediation_report,
            "FAILED",
            [message, "", init_result.stdout, init_result.stderr],
        )
        return RemediationResult(False, True, message, remediation_report)

    apply_command = [
        terraform_binary,
        "apply",
        "-auto-approve",
        "-input=false",
        "-no-color",
    ]
    apply_result = run_command(apply_command, cwd=project_root)
    if apply_result.returncode != 0:
        message = "terraform apply failed during remediation."
        write_report(
            remediation_report,
            "FAILED",
            [message, "", apply_result.stdout, apply_result.stderr],
        )
        return RemediationResult(False, True, message, remediation_report)

    message = "Drift remediated successfully."
    write_report(
        remediation_report,
        "SUCCESS",
        [message, "", init_result.stdout, apply_result.stdout],
    )
    return RemediationResult(True, True, message, remediation_report)


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser."""
    parser = argparse.ArgumentParser(description="Remediate Terraform drift.")
    parser.add_argument(
        "--project-root",
        default=str(Path(__file__).resolve().parent.parent),
        help="Project root directory containing the Terraform configuration.",
    )
    parser.add_argument(
        "--report-file",
        default=str(Path(__file__).resolve().parent.parent / "drift-report.txt"),
        help="Path to the drift report generated by drift-detection/detect.sh.",
    )
    parser.add_argument(
        "--terraform-binary",
        default="terraform",
        help="Terraform executable to invoke.",
    )
    parser.add_argument(
        "--auto-approve",
        action="store_true",
        help="Automatically run terraform apply when drift is detected.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """CLI entry point for drift remediation."""
    parser = build_parser()
    args = parser.parse_args(list(argv) if argv is not None else None)

    project_root = Path(args.project_root)
    report_file = Path(args.report_file)
    result = remediate_drift(
        project_root=project_root,
        report_file=report_file,
        terraform_binary=args.terraform_binary,
        auto_approve=args.auto_approve,
    )

    print(result.message)
    print(f"Report: {result.report_path}")
    return 0 if result.success else 1


if __name__ == "__main__":
    raise SystemExit(main())
